// BoardMosaic (src/features/BoardMosaic.cpp) — the board-scan accumulation
// core (FEATURE_PROPOSALS A1): camera frames warped into a board-space canvas
// with "sharpest tile wins" blending. Synthetic ground truth: a textured
// board image at known px/mm, camera views generated by warping it through
// known poses — so the accumulated mosaic can be compared pixel-wise against
// the ground truth. Pure OpenCV, runs in CI.

#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include <opencv2/imgproc.hpp>

#include "features/BoardMosaic.h"

using Catch::Approx;
using namespace ibom::features;

namespace {

constexpr double kBoardW  = 80.0, kBoardH = 60.0;  // mm
constexpr double kGtPxMm  = 10.0;
constexpr double kMargin  = 2.0;

/// Textured "board" image in PCB space: GT pixel (i,j) ↔ PCB mm (i/10, j/10).
cv::Mat makeGroundTruth()
{
    cv::Mat gt(static_cast<int>(kBoardH * kGtPxMm),
               static_cast<int>(kBoardW * kGtPxMm), CV_8UC3,
               cv::Scalar(40, 90, 50));
    cv::RNG rng(42);
    // Noise everywhere so every tile has texture (sharpness measurable).
    cv::Mat noise(gt.size(), CV_8UC3);
    rng.fill(noise, cv::RNG::UNIFORM, 0, 60);
    gt += noise;
    // "Components": deterministic rectangles.
    for (int i = 0; i < 25; ++i) {
        const int x = rng.uniform(20, gt.cols - 80);
        const int y = rng.uniform(20, gt.rows - 50);
        cv::rectangle(gt, {x, y, rng.uniform(20, 70), rng.uniform(15, 40)},
                      cv::Scalar(rng.uniform(10, 240), rng.uniform(10, 240),
                                 rng.uniform(10, 240)),
                      cv::FILLED);
    }
    return gt;
}

/// Pose for a camera centered on PCB (cx, cy) mm at `scale` px/mm.
cv::Mat poseAt(double cx, double cy, double scale, cv::Size cam)
{
    return (cv::Mat_<double>(3, 3) <<
        scale, 0,     cam.width  / 2.0 - cx * scale,
        0,     scale, cam.height / 2.0 - cy * scale,
        0,     0,     1);
}

/// Render what the camera sees under pose H (PCB mm → image px).
cv::Mat renderCamera(const cv::Mat& gt, const cv::Mat& H, cv::Size cam)
{
    // GT px → PCB mm → image px:  M = H · diag(1/gtPxMm).
    const cv::Mat Sinv = (cv::Mat_<double>(3, 3) <<
        1.0 / kGtPxMm, 0, 0, 0, 1.0 / kGtPxMm, 0, 0, 0, 1);
    cv::Mat camImg;
    cv::warpPerspective(gt, camImg, H * Sinv, cam, cv::INTER_LINEAR);
    return camImg;
}

ibom::BBox boardBBox()
{
    ibom::BBox b;
    b.minX = 0; b.minY = 0; b.maxX = kBoardW; b.maxY = kBoardH;
    return b;
}

/// Mean |mosaic − GT| over the written region (canvas offset = margin).
double meanErrorOverWritten(const BoardMosaic& m, const cv::Mat& gt)
{
    const auto& geo = m.geometry();
    const int offX = static_cast<int>(std::lround(-geo.minXmm * geo.pxPerMm));
    const int offY = static_cast<int>(std::lround(-geo.minYmm * geo.pxPerMm));
    const cv::Rect gtInCanvas(offX, offY, gt.cols, gt.rows);
    cv::Mat diff;
    cv::absdiff(m.image()(gtInCanvas), gt, diff);
    cv::Mat gray;
    cv::cvtColor(diff, gray, cv::COLOR_BGR2GRAY);
    const cv::Mat written = m.writtenMask()(gtInCanvas);
    return cv::mean(gray, written)[0];
}

} // namespace

TEST_CASE("mosaic: sweeping views reconstructs the board", "[mosaic]")
{
    const cv::Mat gt = makeGroundTruth();
    const cv::Size cam(640, 480);

    BoardMosaic m;
    m.initialize(boardBBox(), kGtPxMm, kMargin);
    REQUIRE(m.isInitialized());
    REQUIRE(m.geometry().pxPerMm == Approx(kGtPxMm));
    REQUIRE(m.geometry().widthPx == static_cast<int>((kBoardW + 2 * kMargin) * kGtPxMm));

    // 4×3 sweep, FOV ≈ 64×48 mm at 10 px/mm → generous overlap.
    for (double cy = 10.0; cy <= 50.0; cy += 20.0)
        for (double cx = 10.0; cx <= 70.0; cx += 20.0) {
            const cv::Mat H = poseAt(cx, cy, 10.0, cam);
            REQUIRE(m.accumulate(renderCamera(gt, H, cam), H) > 0);
        }

    REQUIRE(m.coverageFraction() > 0.8);
    REQUIRE(m.framesAccumulated() == 12);
    // Warp round-trip cost only: the mosaic must match the ground truth.
    REQUIRE(meanErrorOverWritten(m, gt) < 6.0);
}

TEST_CASE("mosaic: sharper frame wins the tile, blurred does not regress it", "[mosaic]")
{
    const cv::Mat gt = makeGroundTruth();
    const cv::Size cam(640, 480);
    const cv::Mat H = poseAt(40.0, 30.0, 10.0, cam);
    const cv::Mat sharp = renderCamera(gt, H, cam);
    cv::Mat blurred;
    cv::GaussianBlur(sharp, blurred, {21, 21}, 6.0);

    // Blurred first, sharp repairs it.
    BoardMosaic m;
    m.initialize(boardBBox(), kGtPxMm, kMargin);
    REQUIRE(m.accumulate(blurred, H) > 0);
    const double errBlur = meanErrorOverWritten(m, gt);
    REQUIRE(m.accumulate(sharp, H) > 0);
    const double errSharp = meanErrorOverWritten(m, gt);
    REQUIRE(errSharp < errBlur * 0.6);

    // Sharp first: a later blurred pass must NOT degrade the mosaic.
    BoardMosaic m2;
    m2.initialize(boardBBox(), kGtPxMm, kMargin);
    REQUIRE(m2.accumulate(sharp, H) > 0);
    const double errBefore = meanErrorOverWritten(m2, gt);
    m2.accumulate(blurred, H);   // full tiles must all be rejected
    REQUIRE(meanErrorOverWritten(m2, gt) == Approx(errBefore).margin(0.5));
}

TEST_CASE("mosaic: degenerate inputs are rejected", "[mosaic]")
{
    BoardMosaic m;
    const cv::Mat frame(480, 640, CV_8UC3, cv::Scalar(1, 2, 3));

    // Not initialized yet.
    REQUIRE(m.accumulate(frame, cv::Mat::eye(3, 3, CV_64F)) == 0);

    m.initialize(boardBBox(), kGtPxMm, kMargin);
    REQUIRE(m.accumulate(frame, cv::Mat()) == 0);                       // empty H
    REQUIRE(m.accumulate(frame, cv::Mat::zeros(3, 3, CV_64F)) == 0);    // singular
    REQUIRE(m.accumulate(cv::Mat(), cv::Mat::eye(3, 3, CV_64F)) == 0);  // empty frame

    // Pose looking entirely off-board → no overlap with the canvas.
    const cv::Mat far = poseAt(4000.0, 4000.0, 10.0, {640, 480});
    REQUIRE(m.accumulate(frame, far) == 0);
    REQUIRE(m.coverageFraction() == 0.0);
}

TEST_CASE("mosaic: RAM guard clamps the resolution", "[mosaic]")
{
    BoardMosaic m;
    ibom::BBox huge;
    huge.minX = 0; huge.minY = 0; huge.maxX = 2000.0; huge.maxY = 500.0;
    m.initialize(huge, 50.0, 2.0, 4096);
    REQUIRE(m.isInitialized());
    REQUIRE(std::max(m.geometry().widthPx, m.geometry().heightPx) <= 4096);
    REQUIRE(m.geometry().pxPerMm < 50.0);
}
